server:
  port: 8001
spring:
  application:
    # \u9879\u76EE\u540D\uFF0C\u6CE8\u518C\u4E8Eeurka-server
    name: provider
eureka:
  instance:
    # \u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u4F7F\u7528\u670D\u52A1\u7684ip\u5730\u5740
    prefer-ip-address: true
  client:
    defaultZone: http://localhost:8761/eureka/
