spring:
                    mail:
                      username: 799478052@qq.com
                      password: qhetigxiuvpebehc
                      host: smtp.qq.com
                      properties:
                        mail:
                          smtp:
                            enable: true