spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summer?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: li1234
    # \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # 配置restful请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# \u65E5\u5FD7\u8F93\u51FA
logging:
  level:
    root: warn
    com.li.car.mapper: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.li.car.entity
server:
  port: 8080




