server:
  # \u6307\u5B9A\u7AEF\u53E3
  port: 8761
eureka:
  # eureka\u5B9E\u4F8B\u7684\u4E3B\u673A\u540D
  instance: eureka-server
  client:
    # \u4E0D\u4ECEeureka\u4E0A\u6765\u83B7\u53D6\u670D\u52A1\u7684\u6CE8\u518C\u4FE1\u606F,\u9ED8\u8BA4\u4E3Atrue
    fetch-registry: false
    # \u4E0D\u628A\u81EA\u5DF1\u6CE8\u518C\u5230eureka\u4E0A
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

