spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summer?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: li1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# \u65E5\u5FD7\u8F93\u51FA
logging:
  level:
    root: warn
    com.li.mp.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml