#jdbc配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summer?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: li1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # oracle必须这样配置检查，不了会报检查错误
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置Druid的监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: li
        login-password: 123
        # 添加IP白名单
        allow: 127.0.0.1
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        deny: 192.168.1.103
      web-stat-filter:
        enabled: true
        # 拦截所有请求
        url-pattern: /*
        # 放行静态资源
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
mybatis:
  # 指定全局配置文件的位置
  config-location: classpath:/mybatis/config/MapperConfig.xml
  # 指定sql映射文件的位置
  mapper-locations: classpath:/mybatis/mapper/*.xml
